from datetime import datetime
from typing import List

from miles.plugin_api import Promo


class HelloPlugin:  # matches the SDK
    name = "demo-hello"
    schedule = "@hourly"
    categories = ["bonus"]

    def scrape(self, since: datetime) -> List[Promo]:
        return [
            Promo(
                program="DEMO",
                bonus_pct=42,
                start_dt=None,
                end_dt=None,
                url="https://example.com",
                title="🧪 Demo promo generated by plug-in",
                source=self.name,
            )
        ]
