# fly.toml app configuration file generated for miles on 2025-06-07T09:27:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miles-redis'
primary_region = 'iad'

[build]
dockerfile = 'Dockerfile'

[env]
PYTHONUNBUFFERED = '1'

[http_service]
internal_port = 8080
force_https = false

[[http_service.checks]]
grace_period = "30s"
interval = "60s"
method = "GET"
path = "/health"
port = 8080
protocol = "http"
timeout = "10s"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
