# fly.toml app configuration file generated for miles on 2025-06-07T09:27:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miles'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
