name: bonus-alert
on:
  schedule:
    - cron: '0 * * * *'    # HH:00 UTC
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install requests beautifulsoup4 python-telegram-bot==13.15
      - env:
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
         TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
         run: python $GITHUB_WORKSPACE/bonus_alert_bot.py
