name: bonus-alert

on:
  schedule:
    - cron: '0 15 * * *'
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: ./setup.sh
      - run: pip install pytest
      - run: pytest
      - name: Restore seen cache
        uses: actions/download-artifact@v4
        with:
          name: seen-cache
          path: .
        continue-on-error: true
      - run: |
          if [ -f seen-cache.zip ]; then
            unzip -o seen-cache.zip
          fi
      - env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          MIN_BONUS: ${{ vars.MIN_BONUS }}
          DEBUG_MODE: ${{ vars.DEBUG_MODE }}
          PROGRAMS_JSON: ${{ vars.PROGRAMS_JSON }}
        run: python bonus_alert_bot.py
      - run: zip -9 seen-cache.zip seen.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: seen-cache
          path: seen-cache.zip
