name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.12'
      - run: pip install -e .[dev]
      - run: pre-commit run --all-files
      - name: Run tests
        run: pytest --cov=miles --cov-report=xml 2>&1 | tee test_output.log
      - name: Ship test logs
        if: env.LOG_WEBHOOK_URL != ''
        run: |
          curl -s -X POST "$LOG_WEBHOOK_URL" \
               -H "Content-Type: application/json" \
               -d "{\"run_id\":\"${{ github.run_id }}\",\"step\":\"pytest\",\"log\":\"$(cat test_output.log | jq -Rs .)\"}" || true
        env:
          LOG_WEBHOOK_URL: ${{ secrets.LOG_WEBHOOK_URL }}
      - name: Run mypy
        run: mypy miles 2>&1 | tee mypy_output.log
      - name: Ship mypy logs
        if: env.LOG_WEBHOOK_URL != ''
        run: |
          curl -s -X POST "$LOG_WEBHOOK_URL" \
               -H "Content-Type: application/json" \
               -d "{\"run_id\":\"${{ github.run_id }}\",\"step\":\"mypy\",\"log\":\"$(cat mypy_output.log | jq -Rs .)\"}" || true
        env:
          LOG_WEBHOOK_URL: ${{ secrets.LOG_WEBHOOK_URL }}
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: aquasecurity/trivy-action@v0.27.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH