name: deploy-fly

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Fly CLI"
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
      - name: "Push secrets to Fly"
        run: |
          fly secrets set \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY || 'not_set' }}" \
            TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            MIN_BONUS="${{ secrets.MIN_BONUS || '80' }}" \
            REDIS_URL="${{ secrets.REDIS_URL || 'not_set' }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - uses: superfly/flyctl-actions@1.5
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MIN_BONUS: ${{ secrets.MIN_BONUS }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Check Machine Status
        run: fly machine status -i 080137ef300d58 || true
      - name: Retrieve Machine Logs
        run: fly logs -i 080137ef300d58 || true
